-- Drop your personal plugin specs in this directory.
-- Any .lua file here is auto-imported by lazy.nvim.

-- This file itself is just documentation - it returns an empty table.
-- Any plugin code you uncomment must be moved into the return table at
-- the end of the file.
--
-- See :help noethervim-user-plugins for documentation.
--
-- ── Adding new plugins ───────────────────────────────────────────────────────
--
-- Download plugins from github:
--   { "some/plugin", event = "VeryLazy", opts = {} }
--
-- Local / in-development plugins:
--   { dir = "~/programming/my-plugin", config = function() ... end }
--   { "my-plugin", dev = true, config = function() ... end }   -- uses lazy.nvim dev.path
--
-- ── Overriding existing plugin configuration ─────────────────────────────────
--
-- Use the EXACT same plugin repo string as NoetherVim uses. Your spec is
-- merged with the distro's and applied last. Three rules cover every case:
--
--   1. `opts` tables merge key by key. Name only the keys you want to
--      change; the rest of the plugin's settings stay as they were.
--   2. Lists inside `opts` are REPLACED, not appended. To add to one, use
--      the function form of `opts` shown below.
--   3. `keys`, `cmd`, `event` and `ft` always append, so adding a keymap
--      never removes an existing one.
--
-- Override snacks picker defaults:
--   { "folke/snacks.nvim",
--     opts = { picker = { layout = { preset = "vertical" } } } }
--   Only `picker.layout` changes; the rest of the picker setup is untouched.
--
-- Add extra keymaps to an existing plugin:
--   { "folke/snacks.nvim",
--     keys = { { "<space>fg", function() Snacks.picker.grep() end, desc = "live grep" } } }
--
-- Override blink.cmp completion settings:
--   { "saghen/blink.cmp",
--     opts = { completion = { list = { max_items = 10 } } } }
--
-- Customize completion keybindings (see :help noethervim-completion-custom).
-- Pick the overall Tab philosophy with `completion_style` in
-- lua/user/config.lua; use the specs below to change individual keys on top
-- of it. Keys you do not name keep whatever that style gave them.
--
-- Tab to accept, S-Tab for snippet backward:
--   { "saghen/blink.cmp", opts = { keymap = {
--       ["<Tab>"]   = { "accept", "snippet_forward", "fallback" },
--       ["<S-Tab>"] = { "snippet_backward", "fallback" },
--   } } }
--
-- Enter to accept, Tab/S-Tab to navigate menu:
--   { "saghen/blink.cmp", opts = { keymap = {
--       ["<CR>"]    = { "accept", "fallback" },
--       ["<Tab>"]   = { "select_next", "fallback" },
--       ["<S-Tab>"] = { "select_prev", "fallback" },
--   } } }
--
-- Override cmdline keys only (insert mode unchanged):
--   { "saghen/blink.cmp", opts = { cmdline = { keymap = {
--       preset = "inherit",
--       ["<Tab>"] = { "accept", "fallback" },
--   } } } }
--
-- Choose exactly which LSP servers Mason installs. This is a list (rule 2),
-- so it REPLACES the defaults and anything your enabled bundles added, which
-- is what you want when you would rather not download servers you never use:
--   { "neovim/nvim-lspconfig",
--     opts = { ensure_installed = { "gopls", "rust_analyzer" } } }
--
-- To ADD servers and keep the rest, use the function form of `opts`:
--   { "neovim/nvim-lspconfig",
--     opts = function(_, opts)
--       vim.list_extend(opts.ensure_installed, { "gopls", "rust_analyzer" })
--     end }
--
-- Treesitter parsers are an exception to rule 2: this ADDS `gleam` and
-- keeps the parsers already installed.
--   { "nvim-treesitter/nvim-treesitter",
--     opts = { ensure_installed = { "gleam" } } }
--
-- neotest adapters are the other exception, so your adapter joins the ones
-- your language bundles registered. Use the function form regardless: the
-- adapter object has to be built after its plugin loads, which a table value
-- would be too early for. See :help noethervim-test-adapters.
--   { "nvim-neotest/neotest",
--     dependencies = { "some/neotest-adapter" },
--     opts = function(_, opts)
--       table.insert(opts.adapters, require("neotest-adapter")({}))
--     end }
--
-- ── Disabling a plugin ──────────────────────────────────────────────────────
--
-- Prevent a plugin from loading with cond = false (or enabled = false):
--   { "Chiarandini/snacks-zotero.nvim", cond = false }
--
-- lazy.nvim resolves these on the merged plugin (last-write-wins),
-- and user fragments are always last. `cond = false` keeps the plugin in
-- lazy's disabled list (visible in :Lazy); `enabled = false` removes it
-- entirely.
--
-- Replace a plugin with your own fork:
--   { "Chiarandini/snacks-zotero.nvim", cond = false },
--   { "yourname/snacks-zotero.nvim" },
--
-- To fully remove a bundle, just comment out the import in init.lua.
return {}
