#!/bin/bash
# tests/capability.sh -- Level-C language capability matrix (Phase 1).
#
# Plan: dev-docs/language-matrix-test-plan.md
# Contract being tested: dev-docs/language-bundle-contract.md
#
# Spins an ISOLATED Neovim (own NVIM_APPNAME + XDG dirs under $TMPDIR), loads
# NoetherVim core from THIS checkout plus one language bundle AND the tool
# bundles its checkpoints depend on (test / debug / task-runner), then runs
# tests/capability_assert.lua against a fixture project.
#
# Deliberately a separate root from bundle_load.sh: that harness loads exactly
# one bundle in order to attribute a failure, while these checkpoints only
# exist when a language bundle and a tool bundle are enabled together.
#
# The install root is SHARED across runs and never wiped, so plugins and Mason
# packages install once. Force a clean rebuild with NVCAP_FRESH=1.
#
# Usage:
#   tests/capability.sh rust
#   tests/capability.sh --all
#   NVCAP_FRESH=1 tests/capability.sh go
#
# Exit code: non-zero if any checkpoint FAILs. UNCOVERED (toolchain absent on
# this machine) and N/A (declared in the plan) never gate.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FIXTURES="$SCRIPT_DIR/fixtures/lang"

LANGS=(rust go python c cpp java web latex)

APPNAME="nvim-captest"
HARNESS_ROOT="${TMPDIR:-/tmp}/noethervim-capability-harness"

if [ "${NVCAP_FRESH:-0}" = "1" ]; then
    echo "NVCAP_FRESH=1 -- wiping $HARNESS_ROOT"
    rm -rf "$HARNESS_ROOT"
fi

export XDG_CONFIG_HOME="$HARNESS_ROOT/config"
export XDG_DATA_HOME="$HARNESS_ROOT/data"
export XDG_STATE_HOME="$HARNESS_ROOT/state"
export XDG_CACHE_HOME="$HARNESS_ROOT/cache"
export NVIM_APPNAME="$APPNAME"
CONFIG_DIR="$XDG_CONFIG_HOME/$APPNAME"
mkdir -p "$CONFIG_DIR"

# Safety: never let a bad expansion point this at a real config.
case "$CONFIG_DIR" in
  "$HOME/.config/nvim"|"$HOME/.config/noethervim")
    echo "refusing: resolved config dir is a real one ($CONFIG_DIR)"; exit 2;;
esac

NVTIMEOUT=""
if command -v timeout >/dev/null 2>&1; then NVTIMEOUT="timeout ${NVCAP_TIMEOUT:-420}"
elif command -v gtimeout >/dev/null 2>&1; then NVTIMEOUT="gtimeout ${NVCAP_TIMEOUT:-420}"; fi

# Build artifacts from a previous run would let a stale binary answer for a
# broken command, so every fixture starts clean.
clean_fixtures() {
    rm -rf "$FIXTURES/rust/target" "$FIXTURES/rust/Cargo.lock" \
           "$FIXTURES/go/capfixture" "$FIXTURES/c/main" "$FIXTURES/c/main_debug" "$FIXTURES/c/build" \
           "$FIXTURES/java/target" \
           "$FIXTURES"/*/__pycache__ "$FIXTURES"/*/.pytest_cache 2>/dev/null
}

write_init() {
    # $1 = bundle key, e.g. "languages.rust"
    cat > "$CONFIG_DIR/init.lua" <<LUA
-- GENERATED by tests/capability.sh -- isolated capability-matrix init.
vim.g.mapleader       = "\\\\"
vim.g.maplocalleader  = ","
vim.g.mapsearchleader = "<space>"
vim.g.noethervim_no_user = true
vim.g.noethervim_dev     = true

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  spec = {
    { dir = "$REPO_ROOT", name = "NoetherVim", import = "noethervim.plugins",
      config = function() require("noethervim").setup() end },
    { import = "noethervim.bundles.$1" },
    -- Checkpoints 5 and 6 only exist when a tool bundle is enabled alongside
    -- the language bundle; 7 and 8 want the task runner present too.
    { import = "noethervim.bundles.tools.test" },
    { import = "noethervim.bundles.tools.debug" },
    { import = "noethervim.bundles.tools.task-runner" },
  },
  install = { colorscheme = { "gruvbox", "habamax" } },
  performance = { rtp = { paths = { vim.fn.stdpath("config") } } },
})
LUA
}

bundle_for() {
    case "$1" in
        c|cpp) echo "languages.c-cpp" ;;
        web)   echo "languages.web-dev" ;;
        *)     echo "languages.$1" ;;
    esac
}

# Kept in step with SPECS[<lang>].main in capability_assert.lua: provisioning
# has to open the same file the assertions do, or it warms the wrong server.
main_for() {
    case "$1" in
        rust)   echo "src/main.rs" ;;
        go)     echo "main.go" ;;
        python) echo "main.py" ;;
        c)      echo "main.c" ;;
        java)   echo "src/main/java/capfixture/Main.java" ;;
        web)    echo "main.ts" ;;
        latex)  echo "main.tex" ;;
        cpp)    echo "main.cpp" ;;
    esac
}

run_one() {
    local lang="$1"
    local bundle; bundle="$(bundle_for "$lang")"

    if [ ! -d "$FIXTURES/$lang" ]; then
        echo "=== $lang: NO FIXTURE ($FIXTURES/$lang)"; return 3
    fi

    echo "==================================================================="
    echo "LANGUAGE: $lang   bundle: $bundle"
    echo "isolated env: NVIM_APPNAME=$APPNAME  root=$HARNESS_ROOT"
    clean_fixtures
    write_init "$bundle"

    echo "--- phase 1: lazy install + Mason (shared root; first run slow) ---"
    local t0 t1
    t0=$(date +%s)
    $NVTIMEOUT nvim --headless "+Lazy! install" "+qa" >"$HARNESS_ROOT/install.log" 2>&1

    # `Lazy! install` clones plugins but reads no buffer, and nvim-lspconfig is
    # lazy-loaded on BufReadPre. Without opening a real file of the language,
    # its config never runs, mason-lspconfig's `ensure_installed` never fires,
    # and the language server is simply absent -- which then reads as "the
    # bundle does not attach an LSP" rather than "the harness never installed
    # one". Open the fixture, then wait for Mason to drain.
    #
    # This is the coverage-honesty rule from full-toolchain-sweep-plan.md: a
    # failure must never be a hidden missing tool.
    # Run from inside the fixture. neotest roots an adapter at Neovim's cwd,
    # so launching from the repo made it look for the crate's tests in the
    # repo itself (adapter id "rustaceanvim:/.../NoetherVim", zero positions).
    # Opening a project from within it is also what a user actually does.
    ( cd "$FIXTURES/$lang" && $NVTIMEOUT nvim --headless "$(main_for "$lang")" \
        +"luafile $SCRIPT_DIR/capability_provision.lua" ) >>"$HARNESS_ROOT/install.log" 2>&1
    # neotest-java fetches a junit-platform-console-standalone jar the first
    # time it runs anything. That download does not complete under a headless
    # run, and the symptom is an adapter that discovers the tests and reports
    # no results at all -- indistinguishable from a broken adapter. Fetch it
    # up front, so an UNCOVERED here can never be a hidden missing tool.
    # vitest's first run in a project is a cold start: it resolves and
    # transforms the whole dependency graph before reporting anything. Under
    # --all, with six other languages already having run on the machine, that
    # cold start has outrun the harness's poll budget and produced a green cell
    # in isolation and a red one in the suite. Warm it here so the graded run
    # measures the adapter rather than the transform.
    if [ "$lang" = "web" ]; then
        # node_modules is not committed, so a clean checkout has no vitest at
        # all. Without this the test cell fails for a missing tool rather than
        # reporting UNCOVERED, which is the one thing the coverage rule forbids.
        if [ ! -d "$FIXTURES/web/node_modules" ]; then
            ( cd "$FIXTURES/web" && timeout 600 npm install --silent ) \
              || echo "    warning: npm install failed for the web fixture"
        fi
        ( cd "$FIXTURES/web" && timeout 300 npx vitest run >/dev/null 2>&1 ) || true
    fi

    # compile_commands.json carries an absolute directory, so it is generated
    # here rather than committed: a path from the machine that wrote it is
    # wrong everywhere else, and clangd would resolve includes against it.
    for d in c cpp; do
        if [ -d "$FIXTURES/$d" ]; then
            src="main.c"; cc="cc"
            [ "$d" = "cpp" ] && { src="main.cpp"; cc="c++"; }
            printf '[{"directory":"%s","command":"%s -c %s","file":"%s"}]\n' \
                "$FIXTURES/$d" "$cc" "$src" "$src" > "$FIXTURES/$d/compile_commands.json"
        fi
    done

    # doctest.h backs the C/C++ test fixture and is third-party; fetched
    # rather than vendored, so the repo does not carry 500 KB of someone
    # else's header for one fixture.
    if [ "$lang" = "c" ] && [ ! -f "$FIXTURES/c/doctest.h" ]; then
        curl -fsSL -o "$FIXTURES/c/doctest.h" \
          "https://raw.githubusercontent.com/doctest/doctest/master/doctest/doctest.h" \
          || echo "    warning: doctest.h download failed"
    fi

    if [ "$lang" = "java" ]; then
        local jdir="$XDG_DATA_HOME/$APPNAME/neotest-java"
        local jver
        jver="$(sed -n 's/.*version = "\([0-9.]*\)".*/\1/p' \
            "$XDG_DATA_HOME/$APPNAME/lazy/neotest-java/lua/neotest-java/default_config.lua" 2>/dev/null | head -1)"
        if [ -n "$jver" ] && [ ! -f "$jdir/junit-platform-console-standalone-$jver.jar" ]; then
            mkdir -p "$jdir"
            curl -fsSL -o "$jdir/junit-platform-console-standalone-$jver.jar" \
              "https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/$jver/junit-platform-console-standalone-$jver.jar" \
              || echo "    warning: junit standalone jar download failed"
        fi
    fi

    t1=$(date +%s)
    echo "provisioning finished in $((t1 - t0))s"
    echo "    mason packages: $(ls "$XDG_DATA_HOME/$APPNAME/mason/packages" 2>/dev/null | tr '\n' ' ')"

    # NVCAP_PROBE swaps the assertion script for an ad-hoc one, in the env this
    # language was just provisioned for. Without it, a hand-run probe executes
    # against whatever init.lua the previous language left behind -- which
    # silently tests the wrong bundle.
    local script="${NVCAP_PROBE:-$SCRIPT_DIR/capability_assert.lua}"

    echo "--- phase 2: capability checkpoints ($(basename "$script")) ---"
    ( cd "$FIXTURES/$lang" && CAP_LANG="$lang" CAP_FIXTURES="$FIXTURES" $NVTIMEOUT nvim --headless \
        +"luafile $script" +"qa!" )
    local rc=$?
    echo "--- $lang: exit $rc ---"
    return $rc
}

FAILED=""
if [ "${1:-}" = "--all" ]; then
    for l in "${LANGS[@]}"; do
        run_one "$l" || FAILED="$FAILED $l"
    done
    echo
    echo "==================================================================="
    if [ -n "$FAILED" ]; then
        echo "LANGUAGES WITH FAILING CHECKPOINTS:$FAILED"
        exit 1
    fi
    echo "all languages: no failing checkpoints"
    exit 0
fi

if [ -z "${1:-}" ]; then
    echo "usage: tests/capability.sh <${LANGS[*]}|--all>"; exit 2
fi
run_one "$1"
