--- LuaCATS type declarations for NoetherVim's public API.
---
--- This file has no runtime effect -- it exists so that `lua-language-server`
--- (via `.luarc.json` or `lazydev.nvim`) can offer completion and type
--- diagnostics on the single user-facing surface:
---
---     The data table returned from `lua/user/config.lua`.
---
--- Internal types live next to the modules that use them, with `---@private`
--- annotations on internal helpers.
---
--- Stability: alpha. See dev-docs/architecture.md §1.1 for the deprecation
--- policy. Field renames before the first non-alpha release land directly,
--- without `vim.deprecate` shims.

---@class noethervim.StatuslineConfig
---
--- Heirline-based statusline overrides.
---
---@field colors? table<string, string>
---     Heirline color-table overrides. Keys match heirline's color names
---     (e.g. `mode_n`, `mode_i`, `git_added`); values are hex strings.
---@field extra_right? table[]
---     Extra heirline component specs appended to the right side of the
---     main statusline, after the git block.
---@field edge_style? "round"|"slant"|"pointy"|"straight"|"bubbly"
---     Shape of the colored mode block at the left of the statusline and
---     (for "bubbly", "slant", "pointy") an opening endcap on the right
---     ruler block. Default "round" preserves the historical look.
---     "bubbly" rounds both edges; "straight" disables endcaps entirely.

---@class noethervim.UserConfig
---
--- The data table returned from `lua/user/config.lua`. NoetherVim's
--- single user-facing configuration surface, read by `noethervim.setup()`
--- and by individual bundles when they activate.
---
--- Every field is optional. Missing keys fall back to distro defaults.
---
---@field colorscheme? string
---     Default colorscheme name, applied during setup() unless the
---     colorscheme bundle has persisted a user pick.
---@field colorscheme_persistence? boolean
---     If true, restore the last picked colorscheme on startup. Has no
---     effect unless the colorscheme bundle is enabled.
---@field statusline? noethervim.StatuslineConfig
---     Heirline-based statusline overrides.
---@field obsidian_vault? string
---     Absolute or `~`-prefixed path to your Obsidian vault. Required by the
---     `obsidian` bundle; the bundle no-ops without it.
---@field completion_style? "snippet"|"supertab"|"navigate"
---     Tab-key philosophy for the completion menu. See the cmp plugin
---     spec for the per-style behavior.
---@field blink_conservative_filetypes? string[]
---     Filetypes where blink.cmp's keyword-trigger is suppressed. C-Space
---     and LSP trigger characters still work. Default: `{ "tex", "latex" }`.
---@field blink_conservative_size_kb? integer
---     File size (in KB) above which conservative completion mode kicks in
---     regardless of filetype. Default: 500.
---@field drop? boolean
---     If false, disable seasonal drop.nvim animations. Default: true.
---@field writing_filetypes? string[]
---     Extra filetypes to treat as writing (wrap, linebreak, spell, conceal,
---     formatoptions+t). Extends the distro defaults.
---@field non_code_filetypes? string[]
---     Extra filetypes that skip BOTH writing and code profiles. Extends
---     the distro defaults.
---@field spell_in_code? boolean
---     If true, the code profile enables spellcheck, scoped to comments
---     and strings via treesitter `@spell` captures. Default: false.

return {}
