// Pull user-facing markdown from the repo into the Starlight content
// collection.
//
// The repo's markdown stays canonical -- nothing here is authored by hand,
// and everything written under src/content/docs/{start,guides}/ is
// gitignored. Editing those files is always the wrong move; edit the
// upstream source and re-run.
//
// Run via `npm run sync`, which `prebuild` and `predev` both call.

import { mkdir, readFile, writeFile, copyFile, readdir, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../..');
const out = resolve(here, '../src/content/docs');

// Whole files lifted as-is.
const FILES = [
  {
    src: 'docs/onboarding/README.md',
    dest: 'start/first-session.md',
    title: 'Your first session',
    description: 'Keybinding prefixes, the commands worth running first, and a tour of the defaults.',
    sidebar: 2,
  },
  {
    src: 'docs/onboarding/mathematicians.md',
    dest: 'start/mathematicians.md',
    title: 'For mathematicians',
    description: 'The math bundles, snippets, citations, and how to extend the LaTeX setup.',
    sidebar: 3,
  },
  {
    src: 'docs/bundles.md',
    dest: 'guides/bundles.md',
    title: 'Bundles',
    description: 'Optional feature groups and their dependencies.',
    sidebar: 1,
  },
  {
    src: 'docs/user-config-examples.md',
    dest: 'guides/recipes.md',
    title: 'Recipes',
    description: 'Copy-paste specs for plugins deliberately left out of the distribution.',
    sidebar: 4,
  },
];

// Sections sliced out of README.md by heading. `until` stops the slice at
// the next heading of that level, so a section keeps its subsections.
const SECTIONS = [
  {
    dest: 'start/install.md',
    title: 'Installation',
    description: 'Requirements, the bootstrap command, side-by-side trials, and uninstalling.',
    sidebar: 1,
    headings: ['Requirements', 'Installation'],
  },
  {
    dest: 'guides/configuration.md',
    title: 'Configuration',
    description: 'Enabling bundles, adding plugins, and overriding options and keymaps.',
    sidebar: 2,
    headings: ['Configuration'],
  },
  {
    dest: 'guides/keybindings.md',
    title: 'Keybinding philosophy',
    description: 'Prefix conventions and how to discover what the distro binds.',
    sidebar: 3,
    headings: ['Keybinding Philosophy'],
  },
];

// Repo-relative markdown paths and README anchors to their site routes.
const LINKS = [
  [/\]\(docs\/onboarding\/README\.md\)/g, '](/noethervim/start/first-session/)'],
  [/\]\(docs\/onboarding\/mathematicians\.md\)/g, '](/noethervim/start/mathematicians/)'],
  [/\]\(docs\/user-config-examples\.md\)/g, '](/noethervim/guides/recipes/)'],
  [/\]\(`?docs\/bundles\.md`?(#[a-z-]*)?\)/g, '](/noethervim/guides/bundles/)'],
  [/\]\(#configuration\)/g, '](/noethervim/guides/configuration/)'],
  [/\]\(#bundles\)/g, '](/noethervim/guides/bundles/)'],
  [/\]\(#keybinding-philosophy\)/g, '](/noethervim/guides/keybindings/)'],
  [/\]\(#enabling-bundles\)/g, '](/noethervim/guides/configuration/#enabling-bundles)'],
  [/\]\(#migrating-from-an-existing-config\)/g, '](/noethervim/start/install/#migrating-from-an-existing-config)'],
  [/\]\(docs\/assets\//g, '](/noethervim/assets/'],
  [/\(docs\/assets\//g, '(/noethervim/assets/'],
];

const ASIDES = {
  NOTE: 'note',
  TIP: 'tip',
  IMPORTANT: 'caution',
  WARNING: 'caution',
  CAUTION: 'danger',
};

/** GitHub alert blockquotes -> Starlight asides. */
function convertAsides(md) {
  const lines = md.split('\n');
  const result = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^>\s*\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*$/);
    if (!m) {
      result.push(lines[i]);
      continue;
    }
    const body = [];
    i++;
    while (i < lines.length && lines[i].startsWith('>')) {
      body.push(lines[i].replace(/^>\s?/, ''));
      i++;
    }
    i--;
    result.push(`:::${ASIDES[m[1]]}`, ...body, ':::');
  }
  return result.join('\n');
}

function frontmatter({ title, description, sidebar }) {
  return [
    '---',
    `title: ${JSON.stringify(title)}`,
    `description: ${JSON.stringify(description)}`,
    `sidebar:\n  order: ${sidebar}`,
    'editUrl: false',
    '---',
    '',
    // HTML comment, not MDX `{/* */}`: these are .md files, where MDX comment
    // syntax renders as literal text and creates a phantom TOC entry.
    '<!-- Generated by scripts/sync-docs.mjs. Edit the upstream file, not this. -->',
    '',
  ].join('\n');
}

function rewrite(md) {
  let s = md;
  for (const [pattern, replacement] of LINKS) s = s.replace(pattern, replacement);
  return convertAsides(s);
}

/** Strip the leading h1 and any content before the first real section. */
function stripTitle(md) {
  return md.replace(/^#\s+.*\n+/, '');
}

/** Slice `## <heading>` up to the next `##` or `---` rule. */
function section(md, heading) {
  const start = md.search(new RegExp(`^##\\s+${heading}\\s*$`, 'm'));
  if (start === -1) throw new Error(`README section not found: ${heading}`);
  const rest = md.slice(start);
  const body = rest.slice(rest.indexOf('\n') + 1);
  const end = body.search(/^(##\s+|---\s*$)/m);
  return `## ${heading}\n` + (end === -1 ? body : body.slice(0, end));
}

async function main() {
  // Generated trees are disposable; rebuild them from scratch each run so a
  // renamed or deleted upstream file cannot leave a stale page behind.
  for (const dir of ['start', 'guides']) {
    await rm(join(out, dir), { recursive: true, force: true });
    await mkdir(join(out, dir), { recursive: true });
  }

  for (const f of FILES) {
    const raw = await readFile(join(repo, f.src), 'utf8');
    const body = rewrite(stripTitle(raw));
    await writeFile(join(out, f.dest), frontmatter(f) + body + '\n');
    console.log(`  ${f.src} -> ${f.dest}`);
  }

  const readme = await readFile(join(repo, 'README.md'), 'utf8');
  for (const s of SECTIONS) {
    const body = s.headings.map((h) => section(readme, h)).join('\n');
    await writeFile(join(out, s.dest), frontmatter(s) + rewrite(body) + '\n');
    console.log(`  README.md [${s.headings.join(', ')}] -> ${s.dest}`);
  }

  // Hero and demo GIFs referenced by the ported markdown.
  const assets = resolve(here, '../public/assets');
  await mkdir(assets, { recursive: true });
  for (const name of await readdir(join(repo, 'docs/assets'))) {
    await copyFile(join(repo, 'docs/assets', name), join(assets, name));
    console.log(`  docs/assets/${name} -> public/assets/${name}`);
  }
}

await main();
