-- Generate the bundle reference for the docs site and the README.
--
--   nvim --headless -l tools/gen-docs.lua
--
-- Writes docs-site/src/content/docs/guides/bundles.md and fills the
-- BEGIN/END GENERATED marker blocks in README.md. Both are committed; CI
-- reruns this and fails on a diff.
--
-- Reads every bundle's `@bundle` / `@desc` / `@requires` annotation through
-- util.bundle_meta -- the same parser :checkhealth uses -- so the site, the
-- picker and the health check cannot disagree.
--
-- No plugins are loaded: this only reads files, so it runs on a bare Neovim
-- in CI.

local root = vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':h:h')
vim.opt.rtp:prepend(root)

local bundle_meta = require('noethervim.util.bundle_meta')
local metas = bundle_meta.scan(root .. '/lua/noethervim/bundles')

local errors = {}
local bundles = {}

for _, m in ipairs(metas) do
  vim.list_extend(errors, m.errors)

  local requires = {}
  for _, r in ipairs(m.requires) do
    requires[#requires + 1] = {
      kind = r.kind,
      value = r.value,
      label = r.label,
      why = r.why,
      install = r.install,
      optional = r.optional or false,
    }
  end

  bundles[#bundles + 1] = {
    name = m.name,
    category = m.category,
    desc = m.desc,
    import = ('noethervim.bundles.%s.%s'):format(m.category, m.name),
    requires = requires,
  }
end

if #errors > 0 then
  for _, e in ipairs(errors) do
    io.stderr:write('malformed annotation: ' .. e .. '\n')
  end
  os.exit(1)
end

-- Category display order and labels, mirroring the bundles picker.
local CATEGORIES = {
  { key = 'languages',  label = 'Programming languages' },
  { key = 'tools',      label = 'Tools' },
  { key = 'navigation', label = 'Navigation & editing' },
  { key = 'writing',    label = 'Writing & notes' },
  { key = 'terminal',   label = 'Terminal & environment' },
  { key = 'ui',         label = 'UI & appearance' },
  { key = 'practice',   label = 'Practice & utilities' },
}

-- ── docs-site bundle reference ───────────────────────────────────────
-- Committed rather than generated at site-build time: the site is built by
-- the website-nate repo, which has Node but no Neovim. CI here regenerates
-- and fails on a diff, so the committed copy cannot drift.
--
-- Emitted as plain markdown, not MDX with a JSX loop: Starlight builds its
-- "On this page" nav from markdown headings, and headings produced inside a
-- JSX expression are invisible to it.

local function write(path, body)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ':h'), 'p')
  local fh = assert(io.open(path, 'w'))
  fh:write(body)
  fh:close()
end

local by_category = {}
for _, b in ipairs(bundles) do
  by_category[b.category] = by_category[b.category] or {}
  table.insert(by_category[b.category], b)
end

--- Descriptions carry things like `<C-w>O`, which a markdown parser reads as
--- a raw HTML tag and swallows. Escape the angle brackets.
local function md(s)
  if not s then return '' end
  return (s:gsub('&', '&amp;'):gsub('<', '&lt;'):gsub('>', '&gt;'))
end

local page = {
  '---',
  'title: Bundles',
  'description: Optional feature groups, what each provides, and what it needs installed.',
  'sidebar:',
  '  order: 1',
  'editUrl: false',
  '---',
  '',
  '<!-- Generated by tools/gen-docs.lua from the @requires annotations in',
  '     lua/noethervim/bundles/. Edit the bundle header, not this file. -->',
  '',
  'Bundles are optional feature groups. The core works with none enabled.',
  '',
  'Enable one by uncommenting its `import` line in `~/.config/nvim/init.lua`,',
  'or open `:NoetherVim bundles`, highlight it, and press `<C-y>`. A diff',
  'prompt shows the exact change before anything is written.',
  '',
  ':::note',
  'This page is generated from the same annotations `:checkhealth noethervim`',
  'reads. Run that for the state of the bundles you actually have enabled.',
  ':::',
  '',
}

for _, cat in ipairs(CATEGORIES) do
  local list = by_category[cat.key]
  if list and #list > 0 then
    page[#page + 1] = '## ' .. cat.label
    page[#page + 1] = ''
    for _, b in ipairs(list) do
      page[#page + 1] = ('### `%s`'):format(b.name)
      page[#page + 1] = ''
      if b.desc then
        page[#page + 1] = md(b.desc)
        page[#page + 1] = ''
      end
      page[#page + 1] = '```lua'
      page[#page + 1] = ('{ import = "%s" }'):format(b.import)
      page[#page + 1] = '```'
      page[#page + 1] = ''
      if #b.requires > 0 then
        page[#page + 1] = 'Requires:'
        page[#page + 1] = ''
        for _, r in ipairs(b.requires) do
          local line = ('- **%s**%s'):format(md(r.label), r.optional and ' *(optional)*' or '')
          if r.why then line = line .. ': ' .. md(r.why) end
          page[#page + 1] = line
          if r.install then
            page[#page + 1] = ('  <br />%s'):format(md(r.install))
          end
        end
        page[#page + 1] = ''
      end
    end
  end
end

write(root .. '/docs-site/src/content/docs/guides/bundles.md', table.concat(page, '\n'))

-- ── README generated blocks ──────────────────────────────────────────
-- Two hand-maintained lists used to live here and had already drifted from
-- each other and from the bundles on disk. Both are now filled from the
-- annotations between marker comments.

-- Bundles link to the live docs rather than a repo path: the README is read
-- on GitHub, where a relative link into docs-site/src/ is useless.
local DOCS = 'https://nathanaelsrawley.com/noethervim/guides/bundles/'

local function bundle_table()
  local lines = { '| Category | Bundles |', '|---|---|' }
  for _, cat in ipairs(CATEGORIES) do
    local names = {}
    for _, b in ipairs(by_category[cat.key] or {}) do
      names[#names + 1] = ('[`%s`](%s#%s)'):format(b.name, DOCS, b.name)
    end
    if #names > 0 then
      lines[#lines + 1] = ('| %s | %s |'):format(cat.label, table.concat(names, ', '))
    end
  end
  return table.concat(lines, '\n')
end

local function requirement_list()
  local lines = {}
  for _, b in ipairs(bundles) do
    local parts = {}
    for _, r in ipairs(b.requires) do
      -- Optional extras are left out: this list is "what you must install
      -- before the bundle works at all". :checkhealth reports the rest.
      if not r.optional then
        parts[#parts + 1] = r.label
      end
    end
    if #parts > 0 then
      lines[#lines + 1] = ('- `%s` needs %s'):format(b.name, table.concat(parts, ', '))
    end
  end
  return table.concat(lines, '\n')
end

local BLOCKS = {
  ['bundle-requirements'] = requirement_list(),
  ['bundle-table'] = bundle_table(),
}

local readme_path = root .. '/README.md'
local readme = table.concat(vim.fn.readfile(readme_path), '\n')
local replaced = 0

--- Escape Lua pattern magic so a literal string can be matched.
local function lit(s)
  return (s:gsub('[%^%$%(%)%%%.%[%]%*%+%-%?]', '%%%0'))
end

for name, body in pairs(BLOCKS) do
  local open_tag = ('<!-- BEGIN GENERATED: %s -->'):format(name)
  local close_tag = ('<!-- END GENERATED: %s -->'):format(name)
  -- `.-` spans newlines in Lua patterns, and must also match the empty case
  -- where the two markers sit on consecutive lines.
  local pattern = '(' .. lit(open_tag) .. ').-(' .. lit(close_tag) .. ')'
  local new, n = readme:gsub(pattern, function(o, c)
    return o .. '\n' .. body .. '\n' .. c
  end)
  if n > 0 then
    readme = new
    replaced = replaced + 1
  else
    io.stderr:write(('README.md: no marker block for "%s"\n'):format(name))
  end
end

write(readme_path, readme .. '\n')

io.write(('wrote docs-site bundle reference (%d bundles, %d requirements)\n'):format(
  #bundles, (function()
    local n = 0
    for _, b in ipairs(bundles) do n = n + #b.requires end
    return n
  end)()))
io.write(('rewrote %d README block(s)\n'):format(replaced))
