-- Personal autocommand additions for NoetherVim.
-- Copy this file to lua/user/autocmds.lua and uncomment/add the lines you want.
-- lua/user/autocmds.lua lives in your config, not in the distribution:
-- `git pull` and `:Lazy update` never touch it.
--
-- This file runs after noethervim/autocmds.lua. New autocommands are
-- additive. To override a core autocmd, clear its augroup first.
--
-- See noethervim/autocmds.lua for all defaults.
-- See :help noethervim-user-autocmds for documentation.

-- ── Add an autocommand ───────────────────────────────────────────────────────
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   group    = vim.api.nvim_create_augroup("user_trim_whitespace", { clear = true }),
--   pattern  = "*",
--   callback = function()
--     local pos = vim.api.nvim_win_get_cursor(0)
--     vim.cmd([[%s/\s\+$//e]])
--     vim.api.nvim_win_set_cursor(0, pos)
--   end,
-- })

-- ── Override a core autocommand ──────────────────────────────────────────────
-- To ADD a filetype to the q-to-quit list, set q_close_filetypes in
-- lua/user/config.lua -- no autocmd needed.
--
-- To REMOVE one of the distro's entries, clear the group and re-create the
-- autocmd with your own list:
-- vim.api.nvim_create_augroup("noethervim_q_close", { clear = true })
-- local fts = vim.tbl_filter(
--   function(ft) return ft ~= "diff" end,
--   require("noethervim.util.filetypes").q_close
-- )
-- vim.api.nvim_create_autocmd("FileType", {
--   group   = "noethervim_q_close",
--   pattern = fts,
--   callback = function(ev)
--     vim.keymap.set("n", "q", "<cmd>close<cr>",
--       { buf = ev.buf, silent = true, nowait = true })
--   end,
-- })
