-- Personal keymap overrides for NoetherVim.
-- The fastest way to install this template is `:NoetherVim templates` (or
-- SearchLeader+ct, default <Space>ct): pick `user/keymaps.example.lua` and
-- press <C-y> to stamp it into lua/user/keymaps.lua.  You can also copy
-- it manually if you prefer.
-- lua/user/keymaps.lua is gitignored -- it never ships with the distribution.
--
-- This file runs after noethervim/keymaps.lua AND noethervim/toggles.lua,
-- so any keymap you set here overwrites the distro default.
--
-- NoetherVim keymap philosophy:
--   SearchLeader   fuzzy navigation / search (default: <Space>, set vim.g.mapsearchleader)
--   <Leader>       global actions
--   <LocalLeader>  filetype-specific actions
--   <C-w>          window navigation / management
--   [x / ]x        prev / next directional navigation
--   [ox / ]ox      toggle option on / off
--
-- See noethervim/keymaps.lua and noethervim/toggles.lua for all defaults.
-- See :help noethervim-user-keymaps for documentation.

-- ── Override a core keymap ───────────────────────────────────────────────────
-- NoetherVim maps `;` to `:` (command-line).  Revert to Vim's default
-- (repeat last `f` / `t` / `F` / `T` motion):
-- vim.keymap.set("n", ";", ";")

-- ── Remove a core keymap ─────────────────────────────────────────────────────
-- NoetherVim maps `<C-a>` in insert mode to "select all".  Restore
-- Vim's default (insert previously inserted text):
-- vim.keymap.del("i", "<C-a>")

-- ── Insert-mode escape  ──────────────────────────────────────────────────────
-- NoetherVim doesn't ship `jk` -> <Esc>.  Words containing the literal
-- "jk" (e.g. "rejkindle") would stall while vim waits to see whether
-- the next key completes the mapping; if that tradeoff is fine for you,
-- uncomment:
-- vim.keymap.set("i", "jk", "<Esc>", { desc = "escape to normal mode" })

-- ── Add personal keymaps ─────────────────────────────────────────────────────
-- Use <Leader> for global actions, <LocalLeader> for filetype-specific
-- ones, and SearchLeader (default <Space>) for fuzzy navigation only.
-- (NoetherVim already maps <Leader>i to open init.lua.)
--
-- vim.keymap.set("n", "<Leader>ez", "<cmd>e ~/.zshrc<cr>", { desc = "edit zshrc" })
-- vim.keymap.set("n", "<Leader>cd",
--   function() vim.cmd.cd(vim.fn.expand("%:p:h")) end,
--   { desc = "cd to buffer dir" })

-- ── Override a bundle's keymap ───────────────────────────────────────────────
-- Bundle keymaps work the same way -- set the same lhs and yours wins.
-- Example: if you enable the `yanky` bundle but find <C-p>/<C-n> awkward
-- (they collide with cursor-line muscle memory), remap the cycle keys:
-- vim.keymap.set("n", "<M-p>", "<Plug>(YankyPreviousEntry)", { desc = "prev yank" })
-- vim.keymap.set("n", "<M-n>", "<Plug>(YankyNextEntry)",     { desc = "next yank" })

-- ── Smart <C-a>: increment-dial-or-select-all ────────────────────────────────
-- Vim's <C-a> increments numbers; dial.nvim (already in NoetherVim core)
-- extends it to booleans, and/or, ==/!=, dates, semver, etc.  This wrapper
-- delegates to dial when available, watches `changedtick` to see whether
-- anything actually moved, and falls back to "select-all" when the cursor
-- isn't on an incrementable token.
-- vim.keymap.set("n", "<C-a>", function()
--   require("lazy").load({ plugins = { "dial.nvim" }, show = false })
--   local tick = vim.b.changedtick
--   pcall(require("dial.map").manipulate, "increment", "normal")
--   if vim.b.changedtick == tick then
--     vim.cmd("normal! ggVG")
--   end
-- end, { desc = "dial increment, else select all" })
