-- Personal keymap overrides for NoetherVim.
-- Copy this file to lua/user/keymaps.lua and uncomment/add the lines you want.
-- lua/user/keymaps.lua is gitignored -- it never ships with the distribution.
--
-- This file runs after noethervim/keymaps.lua AND noethervim/toggles.lua,
-- so any keymap you set here overwrites the distro default.
--
-- NoetherVim keymap philosophy:
--   SearchLeader   fuzzy navigation / search (default: <Space>, set vim.g.mapsearchleader)
--   <Leader>       global actions
--   <LocalLeader>  filetype-specific actions
--   <C-w>          window navigation / management
--   [x / ]x        prev / next directional navigation
--   [ox / ]ox      toggle option on / off
--
-- See noethervim/keymaps.lua and noethervim/toggles.lua for all defaults.
-- See :help noethervim-user-keymaps for documentation.

-- ── Override a core keymap ───────────────────────────────────────────────────
-- NoetherVim maps `;` to `:` (command-line).  Revert to Vim's default
-- (repeat last `f` / `t` / `F` / `T` motion):
-- vim.keymap.set("n", ";", ";")

-- ── Remove a core keymap ─────────────────────────────────────────────────────
-- NoetherVim maps `<C-a>` in insert mode to "select all".  Restore
-- Vim's default (insert previously inserted text):
-- vim.keymap.del("i", "<C-a>")

-- ── Add personal keymaps ─────────────────────────────────────────────────────
-- Use <Leader> for global actions, <LocalLeader> for filetype-specific
-- ones, and SearchLeader (default <Space>) for fuzzy navigation only.
-- (NoetherVim already maps <Leader>i to open init.lua.)
--
-- vim.keymap.set("n", "<Leader>ez", "<cmd>e ~/.zshrc<cr>", { desc = "edit zshrc" })
-- vim.keymap.set("n", "<Leader>cd",
--   function() vim.cmd.cd(vim.fn.expand("%:p:h")) end,
--   { desc = "cd to buffer dir" })
